on:
  push:
    branches:
      '*'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: first step
        run: pip install pytest
      - name: third step
        run: INPUT_PASSWORD="password" pytest ./project/test/test_server.py
      - name: fouth step
        run: |
          echo Deploying the project...
          echo Project was deployed!
