name: Example of good enough workflow

on:
  push:
    branches: 
      'master'
  pull_request:
    branches:
      'master'

env:
  python_version: 3.12

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      requirements_path: ./labs/lab4/requirements.txt
    steps:
      - name: Checout repository
        uses: actions/checkout@v4
      - name: Setup Python ${{python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{python_version}}
      - name: Setup needed environment
        run: pip install -r $requirements_path
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
        test_path: ./labs/lab4/requirements.txt
    steps:
      - name: Testing server
        run: |
          INPUT_PASSWORD=${{secrets.SERVER_TEST_PASSWORD}}
          pytest $test_path
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Project deployment
        run: |
          echo Deploying the project...
          echo Project was deployed!
