name: Example of workflow with Vault

on:
  push:
    branches: 
      'master'
  pull_request:
    branches:
      'master'

env:
  python_version: '3.12'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      server_path: ./project/src/server.py
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python ${{env.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.python_version}}
      - name: Build server
        run: python $server_path &
  
  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
        test_path: ./project/test/test_server.py
        requirements_path: ./requirements.txt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python ${{env.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.python_version}}
      - name: Setup needed environment
        run: pip install -r $requirements_path
      - name: Get Secret
        uses: hashicorp/vault-action@v2
        with:
          method: jwt
          url: http://127.0.0.1:8200
          role: git_role
          secrets: secret/data/git_secret password | PASSWORD
      - name: Testing server
        run: |
          echo ${{env.PASSWORD}}
          INPUT_PASSWORD=${{env.PASSWORD}} pytest $test_path
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Project deployment
        run: |
          echo Deploying the project...
          echo Project was deployed!
